install:
  - curl -sLo - https://github.com/moul/travis-docker/raw/master/install.sh | sh -xe

script:
  - echo "==> Building the main Docker image..."
  - ./run 'docker build -f test/Dockerfile-ubuntu14.04 -t nginx_img .  &&  docker run -d -p 80:80 nginx_img  &&  docker run -v $(pwd):/data nginx_img curl -v http://localhost:80/nginx_status -o /data/result-ubuntu14.04'

  - echo "==> Validating the test result..."
  - grep Active result-ubuntu14.04  ||  exit 1

