---
# file: tasks/main.yml
# Top-level installer for Nginx.
#
# @see http://wiki.nginx.org/Install
#

- name: delegate to APT system for installation
  include: use-apt.yml
  when: ansible_pkg_mgr == "apt"





- name: rename default/example conf files in /etc/nginx/conf.d/, if any
  sudo: True
  command: mv -f  "/etc/nginx/conf.d/{{ item }}"  "/etc/nginx/conf.d/{{ item }}.bak"
  with_items:
    - default.conf
    - example_ssl.conf
  ignore_errors: true


- name: copy Nginx main config file from role's default, if necessary
  sudo: True
  template: src=../templates/nginx.conf.j2  dest=/etc/nginx/nginx.conf
  when: nginx_conf_main is not defined
  notify:
    - restart nginx

- name: copy Nginx main config file from playbook's, if any
  sudo: True
  template: src={{ playbook_dir }}/{{ nginx_conf_main }}  dest=/etc/nginx/nginx.conf
  when: nginx_conf_main is defined
  notify:
    - restart nginx

- name: copy other Nginx config files from playbook's, if any
  sudo: True
  template: src={{ playbook_dir }}/{{ item.value.src }}  dest=/etc/nginx/conf.d/{{ item.value.dest }}
  with_dict: nginx_conf_others
  when: nginx_conf_others is defined
  notify:
    - restart nginx
