---
# file: tasks/use-yum.yml
#
# Configure nginx from YUM repository.
#
# @see http://wiki.nginx.org/Install
#

- name: install libselinux-python binary for Ansible to work
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - libsemanage-python



- name: add Nginx official repository for CentOS
  copy: src=../files/nginx.repo.centos dest=/etc/yum.repos.d/nginx.repo
  when: ansible_distribution|lower == "centos"

- name: add Nginx official repository for RHEL
  copy: src=../files/nginx.repo.rhel dest=/etc/yum.repos.d/nginx.repo
  when: ansible_distribution == "Red Hat Enterprise Linux"



- name: install Nginx with specific version
  yum: name={{ item }}  update_cache=yes  state=present
  with_items: [ "nginx-{{ nginx_version }}*" ]
  when: nginx_version is defined

- name: install Nginx with default version
  yum: name={{ item }}  update_cache=yes  state=present
  with_items: [ "nginx" ]
  when: nginx_version is not defined


# @see http://stackoverflow.com/questions/23948527/13-permission-denied-while-connecting-to-upstreamnginx
- name: set (httpd_can_network_connect) flag on and keep it persistent across reboots
  seboolean: name=httpd_can_network_connect state=yes persistent=yes
  #when: ansible_selinux.status == "enabled"



- name: set INIT status and start
  service: name=nginx state=started enabled=yes

#- name: set INIT status (SysV style)
#  command: /sbin/chkconfig nginx on

